examples/X.PagedList.Mvc.Example/Controllers/AjaxController.cs
using System.Linq;
using System.Web.Mvc;

namespace X.PagedList.Mvc.Example.Controllers
{
    public class AjaxController : BaseController
	{
		// Ajax Paging
		public ViewResult Index()
		{
			return View();
		}

		// Ajax Paging (cont'd)
		public ActionResult AjaxPage(int? page)
		{
			var listPaged = GetPagedNames(page); // GetPagedNames is found in BaseController
			if (listPaged == null)
				return HttpNotFound();

			return Json(new
			{
				names = listPaged.ToArray(),
				pager = listPaged.GetMetaData()
			}, JsonRequestBehavior.AllowGet);
		}
    }
}

examples/X.PagedList.Mvc.Example/Controllers/AutomapperController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;

namespace X.PagedList.Mvc.Example.Controllers
{
    public class AutomapperController : Controller
    {
        public class OrderOrderViewModelProfile : Profile
        {
            public override string ProfileName => "Mapping between Order and OrderViewModel";

            public OrderOrderViewModelProfile()
            {
                CreateMap<Order, OrderViewModel>();
            }
        }


        public ActionResult Index(int? page)
        {

            Mapper.Initialize(x => x.AddProfile<OrderOrderViewModelProfile>()); // create mapping between Order and OrderViewModel
            const int pageSize = 2;

            var orders = GetAllOrdersFromDatabase();
            var pagedOrders = orders.ToPagedList(page ?? 1, pageSize);

            var viewmodel = Mapper.Map<IEnumerable<Order>, IEnumerable<OrderViewModel>>(pagedOrders.ToArray()); // convert all the Orders in the paged list into viewmodels
            var pagedViewmodel = new StaticPagedList<OrderViewModel>(viewmodel, pagedOrders.GetMetaData()); // reconsitute a new IPagedList containing the viewmodels

            return View(pagedViewmodel);
        }

        public IEnumerable<Order> GetAllOrdersFromDatabase()
        {
            var jerrysOrder = new Order(
                new Customer { Name = "Jerry Seinfeld" },
                new[] { new OrderLineItem(new Product("Superman Underoos", 17.99m), 7) }
            );
            var georgesOrder = new Order(
                new Customer { Name = "George Costanza" },
                new[] { new OrderLineItem(new Product("Bosco", 4.99m), 15) }
            );
            var kramersOrder = new Order(
                new Customer { Name = "Cosmo Kramer" },
                new[] { new OrderLineItem(new Product("Door Knobs", 7.95m), 30) }
            );
            var elainesOrder = new Order(
                new Customer { Name = "Elaine Benes" },
                new[] { new OrderLineItem(new Product("Sponge", 6.95m), 500) }
            );
            var newmansOrder = new Order(
                new Customer { Name = "Newman" },
                new[] { new OrderLineItem(new Product("Dinosaur DNA", 1500000m), 1) }
            );

            var orders = new List<Order>();
            orders.Add(jerrysOrder);
            orders.Add(georgesOrder);
            orders.Add(kramersOrder);
            orders.Add(elainesOrder);
            orders.Add(newmansOrder);
            return orders;
        }

        public class OrderViewModel
        {
            public string CustomerName { get; set; }
            public decimal Total { get; set; }
        }

        // Example classes from: http://automapper.codeplex.com/wikipage?title=Flattening&referringTitle=Home

        public class Customer
        {
            public string Name { get; set; }
        }

        public class Product
        {
            public Product(string name, decimal price)
            {
                Name = name;
                Price = price;
            }

            public string Name { get; private set; }
            public decimal Price { get; private set; }
        }

        public class OrderLineItem
        {
            public OrderLineItem(Product product, int quantity)
            {
                OrderedProduct = product;
                Quantity = quantity;
            }

            public Product OrderedProduct { get; private set; }
            public int Quantity { get; private set; }

            public decimal GetTotal()
            {
                return OrderedProduct.Price * Quantity;
            }
        }

        public class Order
        {
            public Order(Customer customer, IEnumerable<OrderLineItem> lineItems)
            {
                Customer = customer;
                LineItems = lineItems;
            }

            public Customer Customer { get; private set; }
            public IEnumerable<OrderLineItem> LineItems { get; private set; }

            public decimal GetTotal()
            {
                return LineItems.Sum(x => x.GetTotal());
            }
        }
    }
}

examples/X.PagedList.Mvc.Example/Controllers/BaseController.cs
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;

namespace X.PagedList.Mvc.Example.Controllers
{
    public abstract class BaseController : Controller
    {
		protected IPagedList<string> GetPagedNames(int? page)
		{
			// return a 404 if user browses to before the first page
			if (page.HasValue && page < 1)
				return null;

			// retrieve list from database/whereverand
			var listUnpaged = GetStuffFromDatabase();

			// page the list
			const int pageSize = 20;
			var listPaged = listUnpaged.ToPagedList(page ?? 1, pageSize);

			// return a 404 if user browses to pages beyond last page. special case first page if no items exist
			if (listPaged.PageNumber != 1 && page.HasValue && page > listPaged.PageCount)
				return null;

			return listPaged;
		}

		// in this case we return IEnumerable<string>, but in most
		// - DB situations you'll want to return IQueryable<string>
		protected IEnumerable<string> GetStuffFromDatabase()
		{
			var sampleData = new StreamReader(Server.MapPath("~/App_Data/Names.txt")).ReadToEnd();
			return sampleData.Split('\n');
		}
    }
}

examples/X.PagedList.Mvc.Example/Controllers/HomeController.cs
using System.Web.Mvc;

namespace X.PagedList.Mvc.Example.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

			return View();
		}
	}
}

examples/X.PagedList.Mvc.Example/Controllers/TraditionalPagingController.cs
using System.Web.Mvc;

namespace X.PagedList.Mvc.Example.Controllers
{
    public class TraditionalPagingController : BaseController
    {
		// Traditional Paging
		public ActionResult Index(int? page)
		{
			var listPaged = GetPagedNames(page); // GetPagedNames is found in BaseController
			if (listPaged == null)
				return HttpNotFound();

			// pass the paged list to the view and render
			ViewBag.Names = listPaged;
			return View();
		}
    }
}

examples/X.PagedList.Mvc.Example/Controllers/UnobtrusiveAjaxController.cs
using System.Web.Mvc;

namespace X.PagedList.Mvc.Example.Controllers
{
    public class UnobtrusiveAjaxController : BaseController
    {
		// Unobtrusive Ajax
		public ActionResult Index(int? page)
		{
			var listPaged = GetPagedNames(page); // GetPagedNames is found in BaseController
			if (listPaged == null)
				return HttpNotFound();

			ViewBag.Names = listPaged;
			return Request.IsAjaxRequest()
				? (ActionResult)PartialView("UnobtrusiveAjax_Partial")
				: View();
		}
    }
}

examples/X.PagedList.Mvc.Example/Views/Ajax/Index.cshtml
@{
	ViewBag.Title = "Ajax";
}
@using System.Web.Optimization
@using X.PagedList;


@Styles.Render("~/Content/PagedList.css")

<h2>Ajax Paging</h2>
<ol id="namesList"></ol>
<div id="namesPager"></div>

@section Scripts{
	<script id="namesTemplate" type="text/template">
		{{#each this}}
		<li>{{this}}</li>
		{{/each}}
	</script>
	<script id="pagerTemplate" type="text/template">
		<div class="pagination">
            <ul class="pagination">
                {{#if IsFirstPage}}
                <li class="disabled"><a>««</a></li>
                {{else}}
                <li><a href="/ajax/ajaxpage?page=1">««</a></li>
                {{/if}}

                {{#if HasPreviousPage}}
                <li><a href="/ajax/ajaxpage?page={{PreviousPageNumber}}">«</a></li>
                {{else}}
                <li class="disabled"><a>«</a></li>
                {{/if}}

                {{#unless FirstPageIsVisible}}
                <li class="disabled"><a>...</a></li>
                {{/unless}}

                {{#each Pages}}
                {{#if Selected}}
                <li class="active"><a>{{PageNumber}}</a></li>
                {{else}}
                <li><a href="/ajax/ajaxpage?page={{PageNumber}}">{{PageNumber}}</a></li>
                {{/if}}
                {{/each}}

                {{#unless LastPageIsVisible}}
                <li class="disabled"><a>...</a></li>
                {{/unless}}

                {{#if HasNextPage}}
                <li><a href="/ajax/ajaxpage?page={{NextPageNumber}}">»</a></li>
                {{else}}
                <li class="disabled"><a>»</a></li>
                {{/if}}

                {{#if IsLastPage}}
                <li class="disabled"><a>»»</a></li>
                {{else}}
                <li class="next"><a href="/ajax/ajaxpage?page={{PageCount}}">»»</a></li>
                {{/if}}
            </ul>
		</div>
	</script>

	<script type="text/javascript" src="/Scripts/handlebars-1.0.0.beta.6.js"></script>
	<script type="text/javascript">
		// we use Handlebars.js (http://handlebarsjs.com/) here, but any templating language would work
		var namesTemplate = Handlebars.compile($('#namesTemplate').html());
		var pagerTemplate = Handlebars.compile($('#pagerTemplate').html());

		var fetchPage = function (pageUrl) {
			$.get(pageUrl, function (data) {
				window.location.hash = data.pager.PageNumber;

				// determine how many pages should be shown
				var start, end;
				var numberOfPagesToShowAtOnce = 10;
				var halfOfPagesToShowAtOnce = Math.floor(numberOfPagesToShowAtOnce / 2);
				start = data.pager.PageNumber - halfOfPagesToShowAtOnce;
				if (start < 1)
					start = 1;
				if ((start + numberOfPagesToShowAtOnce) > data.pager.PageCount)
					end = data.pager.PageCount;
				else
					end = start + numberOfPagesToShowAtOnce;

				// add each visible page to an array to show
				data.pager.Pages = [];
				for (var i = start; i <= end; i++) {
					data.pager.Pages.push({
						PageNumber: i,
						Selected: i === data.pager.PageNumber
					});
				}

				// used for showing/hiding ellipsis
				data.pager.FirstPageIsVisible = start === 1;
				data.pager.LastPageIsVisible = end === data.pager.PageCount;

				// add urls for previous & next pages
				data.pager.PreviousPageNumber = data.pager.PageNumber - 1
				data.pager.NextPageNumber = data.pager.PageNumber + 1

				// render templates
				$('#namesList').html(namesTemplate(data.names)).attr('start', data.pager.FirstItemOnPage);
				$('#namesPager').html(pagerTemplate(data.pager));

				// bind to page click events
				$('#namesPager li a').click(function (event) {
					event.preventDefault();
					var newPageUrl = $(event.target).attr('href');
					if (newPageUrl) {
						fetchPage(newPageUrl);
					}
				});
			});
		}

		$(function () {
			var page = window.location.hash
				? window.location.hash.slice(1)
				: 1;
			fetchPage('/ajax/ajaxpage?page=' + page);
		});
	</script>
}

examples/X.PagedList.Mvc.Example/Views/Automapper/Index.cshtml
@{
    ViewBag.Title = "Automapper";
}
@model X.PagedList.IPagedList<X.PagedList.Mvc.Example.Controllers.AutomapperController.OrderViewModel>
@using System.Web.Optimization
@using X.PagedList.Mvc;

@Styles.Render("~/Content/PagedList.css")

<h2>Integrating with <a href="http://automapper.codeplex.com/">AutoMapper</a></h2>
<ul>
	@foreach (var example in Model){ 
		<p>@example.CustomerName: $@example.Total</p>
	}
</ul>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }) )

examples/X.PagedList.Mvc.Example/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

examples/X.PagedList.Mvc.Example/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">@Html.ActionLink("X.PagedList", "Index", "Home")</p>
            </div>
            <div class="float-right">
                <section id="login"></section>
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Traditional", "Index", "TraditionalPaging")</li>
                        <li>@Html.ActionLink("Ajax", "Index", "Ajax")</li>
                        <li>@Html.ActionLink("Unobtrusive Ajax", "Index", "UnobtrusiveAjax")</li>
                        <li>@Html.ActionLink("Automapper", "Index", "Automapper")</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

examples/X.PagedList.Mvc.Example/Views/TraditionalPaging/Index.cshtml
@{
    ViewBag.Title = "Traditional Paging";
}
@using System.Web.Optimization
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common

@Styles.Render("~/Content/PagedList.css")

<h2>Traditional Paging</h2>

<p>Example of paging a list:</p>

@Html.PagedListGoToPageForm((IPagedList)ViewBag.Names, Url.Action("Index"), new GoToFormRenderOptions {InputFieldClass = "form-control", InputWidth = 300, SubmitButtonClass = "btn", SubmitButtonWidth = 100})

<h3>List of @ViewBag.Names.TotalItemCount Names (Page Size: @ViewBag.Names.PageSize, Current Page: @ViewBag.Names.PageNumber)</h3>
<ol start="@ViewBag.Names.FirstItemOnPage">
	@foreach(var i in ViewBag.Names){
		<li>@i</li>
	}
</ol>

<h2>Out-of-the-box Pager Configurations</h2>

<h3>Default Paging Control</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }))

<h3>Classic Paging Control (always shows Previous/Next links, but sometimes they are disabled)</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.Classic)

<h3>Classic Paging Control (Classic +First and Last links)</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)

<h3>Minimal Paging Control</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.Minimal)

<h3>Minimal Paging Control w/ Page Count Text</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.MinimalWithPageCountText)

<h3>Minimal Paging Control w/ Item Count Text</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.MinimalWithItemCountText)

<h3>Page Numbers Only</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.PageNumbersOnly)

<h3>Only Show Five Pages At A Time</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)

<h2>Custom Pager Configurations</h2>

<h3>Custom Wording (<em>Spanish Translation Example</em>)</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), new PagedListRenderOptions { LinkToFirstPageFormat = "<< Primera", LinkToPreviousPageFormat = "< Anterior", LinkToNextPageFormat = "Siguiente >", LinkToLastPageFormat = "Última >>" })

<h3>Show Range of Items For Each Page</h3>
@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), new PagedListRenderOptions { FunctionToDisplayEachPageNumber = page => ((page - 1) * ViewBag.Names.PageSize + 1).ToString() + "-" + (((page - 1) * ViewBag.Names.PageSize) + ViewBag.Names.PageSize).ToString(), MaximumPageNumbersToDisplay = 5 })

<h3>Empty PagedList</h3>
@Html.PagedListPager(new string[0].ToPagedList(1, 10), page => Url.Action("Index", new { page }))

examples/X.PagedList.Mvc.Example/Views/UnobtrusiveAjax/Index.cshtml
@{
	ViewBag.Title = "Unobtrusive Ajax";
}
@using System.Web.Optimization
@using X.PagedList.Mvc;

@Styles.Render("~/Content/PagedList.css")

<h2>Unobtrusive Ajax</h2>

<p>Example of paging a list:</p>
<div id="unobtrusive">
	@Html.Partial("UnobtrusiveAjax_Partial")
</div>
<div id="oncomplete"></div>

@section Scripts{
	<script type="text/javascript" src="/Scripts/jquery.unobtrusive-ajax.min.js"></script>	
	<script>
		function PagedOnComplete(obj) {
			console.log(obj);
			var $oncomplete = $('#oncomplete');
			$oncomplete
				.text('Paging operation completed.')
				.css('backgroundColor', 'yellow')
				.fadeOut({complete: function () {
					$oncomplete.css('backgroundColor', 'transparent').text('').show();
				}});
		}
	</script>
}

examples/X.PagedList.Mvc.Example/Views/UnobtrusiveAjax/UnobtrusiveAjax_Partial.cshtml
@using X.PagedList
@using X.PagedList.Mvc

@Html.PagedListGoToPageForm((IPagedList)ViewBag.Names, Url.Action("Index"))

<ul id="names" start="@ViewBag.Names.FirstItemOnPage">
    @foreach (var i in ViewBag.Names)
    {
        <li>@i</li>
    }
</ul>

@Html.PagedListPager((IPagedList)ViewBag.Names, page => Url.Action("Index", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "unobtrusive", OnComplete = "PagedOnComplete" }))